/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormText: typeof import('bootstrap-vue-next')['BFormText']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BNav: typeof import('bootstrap-vue-next')['BNav']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BToastOrchestrator: typeof import('bootstrap-vue-next')['BToastOrchestrator']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    PasswordModal: typeof import('./src/components/PasswordModal.vue')['default']
  }
}
