/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormInvalidFeedback: typeof import('bootstrap-vue-next')['BFormInvalidFeedback']
    BFormText: typeof import('bootstrap-vue-next')['BFormText']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BNav: typeof import('bootstrap-vue-next')['BNav']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BOffcanvas: typeof import('bootstrap-vue-next')['BOffcanvas']
    BToastOrchestrator: typeof import('bootstrap-vue-next')['BToastOrchestrator']
    DeviceFormOffcanvas: typeof import('./src/components/DeviceFormOffcanvas.vue')['default']
    DeviceGrid: typeof import('./src/components/DeviceGrid.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    PasswordModal: typeof import('./src/components/PasswordModal.vue')['default']
  }
}
